frameworkVersion: '3'

org: eduardylopes
app: duochat-serverless
service: duochat

plugins:
    - serverless-offline
    - serverless-dotenv-plugin

provider:
    name: aws
    runtime: nodejs16.x
    region: ${self:custom.region}
    stage: ${self:custom.stage}
    websocketsApiName: ${self:custom.projectName}
    websocketsApiRouteSelectionExpression: $request.body.route
    logs:
        websocket:
            level: INFO
            role: arn:aws:iam::531107396150:role/ApiGatewayLogsRole

    iamRoleStatements:
        - Effect: Allow
          Action:
              - cloudwatch:*
          Resource: '*'

functions:
    - ${file(src/services/lobby/serverless.yml):functions}
    - ${file(src/services/user/serverless.yml):functions}
    - ${file(src/services/room/serverless.yml):functions}
    - ${file(src/services/web-socket/serverless.yml):functions}

custom:
    projectName: duochat
    region: us-east-1
    stage: develop
    dotenv:
        path: .env
