frameworkVersion: '3'

org: eduardylopes
app: duochat-serverless
service: duochat

plugins:
    - serverless-dynamodb-local
    - serverless-offline

provider:
    name: aws
    runtime: nodejs16.x
    region: us-east-1
    stage: develop
    websocketsApiName: ${self:custom.projectName}
    websocketsApiRouteSelectionExpression: $request.body.route
    logs:
        websocket:
            level: INFO
            role: arn:aws:iam::531107396150:role/ApiGatewayLogsRole

    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:*
              - cloudwatch:*
          Resource: '*'

    environment:
        DUOCHAT_TABLE: '${self:service}-${self:provider.stage}'
        REGION: 'sa-east-1'

custom:
    projectName: duochat
    dynamodb:
        start:
            migrate: true
        stages:
            - develop

functions:
    connect:
        handler: src/lambdas/connect.handler
        events:
            - websocket:
                  route: $connect
    disconnect:
        handler: src/lambdas/disconnect.handler
        events:
            - websocket:
                  route: $disconnect
    default:
        handler: src/lambdas/default.handler
        events:
            - websocket:
                  route: $default

    createRoom:
        handler: src/lambdas/create-room.handler
        events:
            - http:
                  path: /room
                  method: POST
                  cors: true
                  request:
                      schemas:
                          application/json:
                              schema: ${file(src/schemas/create-room-schema.json)}
                              name: create-room-schema

resources:
    Resources:
        DuoChatTable:
            Type: AWS::DynamoDB::Table
            Properties:
                AttributeDefinitions:
                    - AttributeName: PK
                      AttributeType: S
                    - AttributeName: SK
                      AttributeType: S
                    - AttributeName: GSIPK
                      AttributeType: S
                    - AttributeName: GSISK
                      AttributeType: S
                KeySchema:
                    - AttributeName: PK
                      KeyType: HASH
                    - AttributeName: SK
                      KeyType: RANGE
                GlobalSecondaryIndexes:
                    - IndexName: RoomIdIndex
                      KeySchema:
                          - AttributeName: GSIPK
                            KeyType: HASH
                          - AttributeName: GSISK
                            KeyType: RANGE
                      Projection:
                          ProjectionType: 'ALL'
                BillingMode: PAY_PER_REQUEST
                TableName: '${self:service}-${self:provider.stage}'
