frameworkVersion: '3'

org: eduardylopes
app: duochat-serverless
service: duochat

plugins:
    - serverless-offline
    - serverless-dotenv-plugin

provider:
    name: aws
    runtime: nodejs16.x
    region: us-east-1
    stage: develop
    websocketsApiName: ${self:custom.projectName}
    websocketsApiRouteSelectionExpression: $request.body.route
    logs:
        websocket:
            level: INFO
            role: arn:aws:iam::531107396150:role/ApiGatewayLogsRole

    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:*
              - cloudwatch:*
          Resource: '*'

    environment:
        AWS_APPLICATION_REGION: 'sa-east-1'

custom:
    projectName: duochat
    dotenv:
        path: .env

functions:
    connect:
        handler: src/lambdas/connect.handler
        events:
            - websocket:
                  route: $connect
    disconnect:
        handler: src/lambdas/disconnect.handler
        events:
            - websocket:
                  route: $disconnect
    default:
        handler: src/lambdas/default.handler
        events:
            - websocket:
                  route: $default

    createRoom:
        handler: src/lambdas/create-room.handler
        events:
            - http:
                  path: /room
                  method: POST
                  cors: true
                  request:
                      schemas:
                          application/json:
                              schema: ${file(src/models/create-room-model.json)}
                              name: CreateRoomModel
    updateRoom:
        handler: src/lambdas/update-room.handler
        events:
            - http:
                  path: /room
                  method: PUT
                  cors: true
                  request:
                      schemas:
                          application/json:
                              schema: ${file(src/models/update-room-model.json)}
                              name: UpdateRoomModel
