functions:
    connect:
        handler: src/services/web-socket/lambdas/connect.handler
        events:
            - websocket:
                  route: $connect
    disconnect:
        handler: src/services/web-socket/lambdas/disconnect.handler
        events:
            - websocket:
                  route: $disconnect
    default:
        handler: src/services/web-socket/lambdas/default.handler
        events:
            - websocket:
                  route: $default
    getConnectionId:
        handler: src/services/web-socket/lambdas/get-connection-id.handler
        events:
            - websocket:
                  route: getConnectionId
    joinRoom:
        handler: src/services/web-socket/lambdas/join-room.handler
        events:
            - websocket:
                  route: joinRoom
    joinLobby:
        handler: src/services/web-socket/lambdas/join-lobby.handler
        events:
            - websocket:
                  route: joinLobby
